api:
  dashboard: true

entryPoints:
  web:
    address: ':80'
  web-secure:
    address: ':443'

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      httpChallenge:
        entryPoint: web
